# Generated by GitHub Copilot on 2026-05-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pricebudget_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('points_delta', models.IntegerField()),
                ('event_type', models.CharField(choices=[('daily_bonus', 'Daily Bonus'), ('add_price', 'Add Price'), (
                    'confirm_price', 'Confirm Price'), ('manual_award', 'Manual Award')], max_length=40)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='point_ledger_entries', to='api.pricebudgetuser')),
            ],
            options={
                'db_table': 'pricebudget_points_ledger',
            },
        ),
        migrations.AddIndex(
            model_name='pointledger',
            index=models.Index(
                fields=['user', 'created_at'], name='pricebudget_user_created_idx'),
        ),
    ]
